version: '3'

services:
  # --- Web Server Replika 1 ---
  app1:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network

  # --- Web Server Replika 2 ---
  app2:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network
  
  # --- Web Server Replika 3 (Opsional) ---
  app3:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network

  # --- Load Balancer ---
  loadbalancer:
    image: nginx:alpine
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8888:80"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
